### ISSUE TITLE
manage_tftpd_py broken

### ISSUE THREAD

**Issue by lassizci** [cobbler/cobbler#287]
Python tftpd is no longer usable with cobbler as Templar no longer allows calls without valid config. When a client tries tftp, tftpd.py throws an error:

templar.py:59:**init**:AttributeError: 'NoneType' object has no
attribute 'api'

Traceback (most recent call last):
  File "/usr/sbin/tftpd.py", line 1147, in <module>
    sys.exit(main())
  File "/usr/sbin/tftpd.py", line 1125, in main
    templar = cobbler.templar.Templar(None)
  File "/usr/lib/python2.6/site-packages/cobbler/templar.py", line 59,
in **init**
    self.api         = config.api
AttributeError: 'NoneType' object has no attribute 'api'

that is caused by commit 3a25e6a6bf609168f41e4215397a0b4d299490e1
