### ISSUE TITLE
cobbler import fails

### ISSUE THREAD

**Issue by needacobbler** [cobbler/cobbler#2544]
### Describe the bug
Trying to import cobbler image fails.

```
cobbler import --name=centos-8-x86_64 --path=/mnt/iso2
task started: 2021-02-15_135148_import
task started (id=Media import, time=Mon Feb 15 13:51:48 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Exception occurred: <class 'AttributeError'>
Exception value: 'NoneType' object has no attribute 'get_import_manager'
Exception Info:
  File "/usr/local/lib/python3.6/site-packages/cobbler/remote.py", line 98, in run
    rc = self._run(self)

  File "/usr/local/lib/python3.6/site-packages/cobbler/remote.py", line 305, in runner
    self.logger

  File "/usr/local/lib/python3.6/site-packages/cobbler/api.py", line 1501, in import_tree
    import_module = self.get_module_by_name("managers.import_signatures")\

!!! TASK FAILED !!!
```

### Additional context

git install on Centos 8.3 system.  Fails installing Centos 8.2 and 8.3 images.
Previously worked on git install of cobbler 3.0 on Centos 8.2 system with Centos 8.2 image.

**Comment by SchoolGuy** [comment]
@needacobbler I will very much try to fix it with 3.2.1 due to the amount of people working on this project this will take a while but thanks for the report! Your name is just astonishing cool! 🥳

**Comment by SchoolGuy** [comment]
That one seems easy to fix. I will do it tomorrow when I am on my desk again.

**Comment by SchoolGuy** [comment]
Okay I noticed that the `import_signature.py` file had no typing (as many many places we touch) and only basic testcoverage. Thus I will add that with a PR. With these tests we should see if the code behind that line of code fails.

**Comment by SchoolGuy** [comment]
Okay I was finally able to reproduce with @nodeg

We found one error but there are more. We are investigating.

**Comment by nodeg** [comment]
I was able to reproduce this issue on the `master` branch on openSUSE Leap 15.2 but not on  openSUSE Tumbleweed.

```shell
$ cobbler version
Cobbler 3.2.0
  source: 8af5f420, Thu Feb 18 07:08:32 2021 +0100
  build time: Thu Feb 18 10:51:25 2021
```

I worked with 2 ISOs. One is a full DVD where `cobbler import` should work and the other is a netinstall/live ISOs where `cobbler import` should not work. 

```shell
$ mount
(...)
/home/dom/CentOS-8.3.2011-x86_64-boot.iso on /home/dom/centos_boot type iso9660 (ro,relatime,nojoliet,check=s,map=n,blocksize=2048)
/home/dom/CentOS-8.3.2011-x86_64-dvd1.iso on /home/dom/centos_dvd type iso9660 (ro,relatime,nojoliet,check=s,map=n,blocksize=2048)
```

When trying the `netinstall/live` ISO `cobbler import` fails but not the expected way. See #2195.



```shell
$ cobbler import --name=centos8_boot --path=/home/dom/centos_boot
task started: 2021-02-18_123638_import
task started (id=Media import, time=Thu Feb 18 12:36:38 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Exception occurred: <class 'AttributeError'>
Exception value: 'NoneType' object has no attribute 'get_import_manager'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 98, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 305, in runner
    self.logger

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1502, in import_tree
    import_module = self.get_module_by_name("managers.import_signatures")\

!!! TASK FAILED !!!
```

When using the full DVD ISO, `cobbler import` still fails the same way as above, which should not happen.

```shell
$ cobbler import --name=centos8_dvd --path=/home/dom/centos_dvd
task started: 2021-02-18_123716_import
task started (id=Media import, time=Thu Feb 18 12:37:16 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Exception occurred: <class 'AttributeError'>
Exception value: 'NoneType' object has no attribute 'get_import_manager'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 98, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 305, in runner
    self.logger

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1502, in import_tree
    import_module = self.get_module_by_name("managers.import_signatures")\

!!! TASK FAILED !!!
```

I digged a little bit deeper and found out that I did not had all Python3 dependencies installed, although I installed everything via the package manager (zypper):

```shell
$ sudo pip3 install dnspython   
Collecting dnspython
  Downloading dnspython-2.1.0-py3-none-any.whl (241 kB)
     |████████████████████████████████| 241 kB 4.4 MB/s 
Installing collected packages: dnspython
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cobbler 3.2.0 requires Django, which is not installed.
cobbler 3.2.0 requires file-magic, which is not installed.
cobbler 3.2.0 requires ldap3, which is not installed.
cobbler 3.2.0 requires mod_wsgi, which is not installed.
cobbler 3.2.0 requires pymongo, which is not installed.
cobbler 3.2.0 requires tornado, which is not installed.
Successfully installed dnspython-2.1.0
```
After installing the missing ones with pip and retesting `cobbler import` it works as expected. The netinstall/live ISO fails

```shell
$ sudo pip3 install django file-magic ldap3 mod_swgi pymongo tornado
(...)

$ cobbler import --name=centos8_boot --path=/home/dom/centos_boot
task started: 2021-02-18_131554_import
task started (id=Media import, time=Thu Feb 18 13:15:54 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=suse, version=opensuse15generic
Found a candidate signature: breed=suse, version=sles15generic
Exception occurred: <class 'KeyError'>
Exception value: 'signatures'
Exception Info:
  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 98, in run
    rc = self._run(self)

  File "/usr/lib/python3.6/site-packages/cobbler/remote.py", line 305, in runner
    self.logger

  File "/usr/lib/python3.6/site-packages/cobbler/api.py", line 1504, in import_tree
    import_module.run(path, mirror_name, network_root, autoinstall_file, arch, breed, os_version)

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 191, in run
    self.signature = self.scan_signatures()

  File "/usr/lib/python3.6/site-packages/cobbler/modules/managers/import_signatures.py", line 224, in scan_signatures
    for sig in sigdata["breeds"][breed][version]["signatures"]:

!!! TASK FAILED !!!
```
and the full DVD gets successfully imported.

```shell
$ cobbler import --name=centos8_dvd --path=/home/dom/centos_dvd
task started: 2021-02-18_131939_import
task started (id=Media import, time=Thu Feb 18 13:19:39 2021)
running python triggers from /var/lib/cobbler/triggers/task/import/pre/*
running shell triggers from /var/lib/cobbler/triggers/task/import/pre/*
shell triggers finished successfully
Found a candidate signature: breed=redhat, version=rhel8
Found a matching signature: breed=redhat, version=rhel8
Adding distros from path /srv/www/cobbler/distro_mirror/centos8_dvd:
creating new distro: centos8_dvd-x86_64
trying symlink: /srv/www/cobbler/distro_mirror/centos8_dvd -> /srv/www/cobbler/links/centos8_dvd-x86_64
creating new profile: centos8_dvd-x86_64
associating repos
checking for rsync repo(s)
checking for rhn repo(s)
checking for yum repo(s)
starting descent into /srv/www/cobbler/distro_mirror/centos8_dvd for centos8_dvd-x86_64
processing repo at : /srv/www/cobbler/distro_mirror/centos8_dvd/AppStream
need to process repo/comps: /srv/www/cobbler/distro_mirror/centos8_dvd/AppStream
looking for /srv/www/cobbler/distro_mirror/centos8_dvd/AppStream/repodata/*comps*.xml
Keeping repodata as-is :/srv/www/cobbler/distro_mirror/centos8_dvd/AppStream/repodata
processing repo at : /srv/www/cobbler/distro_mirror/centos8_dvd/BaseOS
need to process repo/comps: /srv/www/cobbler/distro_mirror/centos8_dvd/BaseOS
looking for /srv/www/cobbler/distro_mirror/centos8_dvd/BaseOS/repodata/*comps*.xml
Keeping repodata as-is :/srv/www/cobbler/distro_mirror/centos8_dvd/BaseOS/repodata
*** TASK COMPLETE ***

$ cobbler list                                                 
distros:
   centos8_dvd-x86_64

profiles:
   centos8_dvd-x86_64

systems:

repos:

images:

mgmtclasses:

packages:

files:
```

@needacobbler could you verify that you have all dependencies installed via pip and then try to reproduce the issue, please?

**Comment by nodeg** [comment]
As the import work as intended, I see no reason to invest here further. But there wil be an improved version of `cobbler check` where every needed dependency will be checked.

**Comment by SchoolGuy** [comment]
I will close this issue as this will be worked on via #2316.
